---
title: "tfbt on marbles"
author: "mht"
date: "February 24, 2015"
output: html_document
---

```{r}
library(tidyr)
library(dplyr)
setwd("/Users/titlis/cogsci/projects/stanford/projects/thegricean_sinking-marbles/bayesian_data_analysis/")

# level 2 model
d <- read.csv('inferBinomialParams.csv',header=F)
# level 1 model
d <- read.csv('inferBinomialParams_level1model.csv',header=F)

# level 1 model
d.tidy <- d %>% 
  select(V1,V2,V5,V6) %>%
  rename(item = V1,
         exp.val = V2,
         phi = V5,
         theta = V6) %>%
  gather(parameter, value, -item)

# level 2 model
# note: this theta is actually a posterior predictive
d.tidy <- d %>% 
  rename(item = V1,
         exp.val = V2,
         gamma = V3,
         delta = V4,
         phi = V5,
         theta = V6) %>%
  gather(parameter, value, -item)

# take a random subset of 10 items
d.tidy.randomsample<- d.tidy[d.tidy$item%in%sample(levels(d.tidy$item),10),]

ggplot(data=d.tidy.randomsample, aes(x = value))+
  facet_grid(item~parameter,scales='free')+
  geom_histogram()
```

Get some pointwise stats.

```{r, echo=FALSE}

d.stats <- d.tidy %>%
  group_by(item, parameter) %>%
  summarise(mn = mean(value))

ggplot(data=d.stats, aes(x=mn))+
  facet_wrap(~parameter,scales='free')+
  geom_histogram()

```

Compare expected value (mean of responses) to posterior predictive over theta, over gamma (very similar to theta), and phi

```{r}

d.spr <- d.stats %>%
  spread(parameter,mn)

ggplot(data=d.spr, aes(x=exp.val, y = theta))+
  geom_point()

ggplot(data=d.spr, aes(x=exp.val, y = gamma))+
  geom_point()

# j's prediction: N-shaped
ggplot(data=d.spr, aes(x=exp.val, y = phi))+
  geom_point()

# should be less correlated, because it is already taking into account guessing
ggplot(data=d.spr, aes(x=theta, y = phi))+
  geom_point()

```