---
title: "wonky-priors-bda"
author: "mht"
date: "September 21, 2015"
output: html_document
---

```{r helpers}

library(coda)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10)   
```

Load prior data, convert histogram from wppl into samples, calculate credible intervals, plot


```{r}

mhiter <- 100000
burn <- mhiter/2
samples <- mhiter - burn
fpath<- "~/Documents/research/sinking-marbles/bayesian_model_comparison/priors/results/"
prefix <- "priorBDA-binomials_incrMH"
prefix <- "priorBDA-binomials-phi_incrMH"
prefix <- "priorBDA-binomials-byItemPhi_incrMH"

d0<-read.csv(paste(fpath, prefix, mhiter, "burn",  burn, ".csv", sep=""))



d.params <- data.frame(Parameter = rep(d0$Parameter, 
                                         1+samples*d0$Probability),
                         Item = rep(d0$Item, 
                                    1+samples*d0$Probability),
                         Response = rep(d0$Value, 
                                        1+samples*d0$Probability))



```

Global parameters (e.g. noise parameter)
```{r}
d.global<-d.params %>% filter(Item=='global')

ggplot(d.global, aes(x=Response))+
  geom_histogram(aes(y=..count../sum(..count..)))+
  facet_wrap(~Parameter)

plotname <- paste("phiPosterior-"prefix, mhiter/100, "kBurn", burn/100, "k.pdf", sep='')
ggsave(file=paste(fpath, plotname, sep=''), 
       width = 8, height = 5)
```


By item CIs

```{r}
d.tidy <- d.params %>% filter(Item!='global') %>% 
  group_by(Parameter,Item) %>%
  summarise(MAP = estimate_mode(Response),
            credLow = HPDlo(Response),
            credHigh = HPDhi(Response))

ggplot(d.tidy, aes(x=Item, y = MAP))+
  geom_bar(stat='identity', position=position_dodge(), alpha=0.4)+
  geom_errorbar(aes(ymin = credLow, ymax = credHigh))+
  facet_wrap(~Parameter)+
  theme(axis.text.x = element_text(angle=45))+
  coord_flip()+
  ylab("inferred base rate (binomial p)")

plotname <- paste("thetaCI-",prefix, mhiter/100, "kBurn", burn/100, "k.pdf", sep='')
ggsave(file=paste(fpath, plotname, sep=''), 
       width = 20, height = 20)

```

By item Posteriors

```{r}
ggplot(d.params %>% filter(Parameter=='theta'), aes(x=Response))+
  geom_histogram()+ 
  facet_wrap(~Item)

plotname <- paste("thetaPosteriors-",prefix, mhiter/100, "kBurn", burn/100, "k.pdf", sep='')
ggsave(file=paste(fpath, plotname, sep=''), 
       width = 30, height = 20)



ggplot(d.params %>% filter(Parameter=='phi'), aes(x=Response))+
  geom_histogram()+ 
  facet_wrap(~Item)

plotname <- paste("phiPosteriors-",prefix, mhiter/100, "kBurn", burn/100, "k.pdf", sep='')
ggsave(file=paste(fpath, plotname, sep=''), 
       width = 20, height = 20)
```

